name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
        stability:
          - prefer-lowest
          - stable

    name: "P8.{{ matrix.php }} - {{ matrix.stability }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
        env:
          verbose: true

      - name: Install dependencies (${{ matrix.stability }})
        run: composer update --no-interaction --no-progress --${{ matrix.stability }}

      - name: Run Pest tests
        run: ./vendor/bin/pest 